import React, { useState, useEffect } from 'react';
import {
  ShieldAlert,
  Search,
  Filter,
  ArrowRight,
  UserCheck,
  AlertCircle,
  Clock,
  ChevronRight,
  User,
  X
} from 'lucide-react';
import { alertService } from '../services/alertService.js';
import { AlertStatusBadge } from '../components/alerts/AlertStatusBadge.jsx';
import { AlertPriorityBadge } from '../components/alerts/AlertPriorityBadge.jsx';
import { formatINR, formatDateTime } from '../utils/formatters.js';

export const AlertManagementPage = ({
  onSelectAlert,
  onViewCustomer = null,
  initialStatus = '',
  initialSearch = ''
}) => {
  const [alerts, setAlerts] = useState([]);
  const [statusCounts, setStatusCounts] = useState({ OPEN: 0, UNDER_REVIEW: 0, ESCALATED: 0, CLOSED: 0 });
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState(initialSearch || '');
  const [selectedStatus, setSelectedStatus] = useState(initialStatus || '');
  const [selectedPriority, setSelectedPriority] = useState('');
  const [sarOnly, setSarOnly] = useState(false);

  useEffect(() => {
    if (initialStatus !== undefined) setSelectedStatus(initialStatus);
    if (initialSearch !== undefined) setSearch(initialSearch);
  }, [initialStatus, initialSearch]);

  const fetchAlerts = async (searchTerm = search) => {
    try {
      setLoading(true);
      const res = await alertService.getAlerts({
        search: searchTerm?.trim() || undefined,
        status: selectedStatus || undefined,
        priority: selectedPriority || undefined,
        sarCandidate: sarOnly ? true : undefined,
        limit: 50
      });
      if (res.success) {
        setAlerts(res.data.alerts);
        setStatusCounts(res.data.statusCounts);
      }
    } catch (err) {
      console.error('Failed to load alerts:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchAlerts();
  }, [selectedStatus, selectedPriority, sarOnly]);

  const handleSearchSubmit = (e) => {
    e.preventDefault();
    fetchAlerts(search);
  };

  const handleClearSearch = () => {
    setSearch('');
    fetchAlerts('');
  };

  return (
    <div className="space-y-6 text-xs">
      {/* Top Banner / Metrics */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold text-white tracking-tight flex items-center gap-2">
            <ShieldAlert className="h-6 w-6 text-indigo-400" />
            Alert Management & Triage Queue
          </h2>
          <p className="text-xs text-slate-400 mt-0.5">
            Monitor, investigate, and disposition alerts generated by the AML Rule & Scoring Engine.
          </p>
        </div>

        {/* Status Count Chips */}
        <div className="flex items-center gap-2 overflow-x-auto pb-1">
          <button
            onClick={() => setSelectedStatus('')}
            className={`px-3 py-1.5 rounded-lg text-xs font-semibold border transition ${
              selectedStatus === ''
                ? 'bg-indigo-600 text-white border-indigo-500 shadow-sm'
                : 'bg-slate-900/60 text-slate-400 border-slate-800 hover:text-white'
            }`}
          >
            All Alerts ({statusCounts.OPEN + statusCounts.UNDER_REVIEW + statusCounts.ESCALATED + statusCounts.CLOSED})
          </button>

          <button
            onClick={() => setSelectedStatus('OPEN')}
            className={`px-3 py-1.5 rounded-lg text-xs font-semibold border transition flex items-center gap-1.5 ${
              selectedStatus === 'OPEN'
                ? 'bg-amber-500 text-slate-950 border-amber-400 font-bold'
                : 'bg-slate-900/60 text-amber-400 border-amber-500/30 hover:bg-slate-900'
            }`}
          >
            <span className="h-1.5 w-1.5 rounded-full bg-amber-400" />
            Open ({statusCounts.OPEN})
          </button>

          <button
            onClick={() => setSelectedStatus('UNDER_REVIEW')}
            className={`px-3 py-1.5 rounded-lg text-xs font-semibold border transition flex items-center gap-1.5 ${
              selectedStatus === 'UNDER_REVIEW'
                ? 'bg-sky-500 text-slate-950 border-sky-400 font-bold'
                : 'bg-slate-900/60 text-sky-400 border-sky-500/30 hover:bg-slate-900'
            }`}
          >
            <span className="h-1.5 w-1.5 rounded-full bg-sky-400" />
            Under Review ({statusCounts.UNDER_REVIEW})
          </button>

          <button
            onClick={() => setSelectedStatus('ESCALATED')}
            className={`px-3 py-1.5 rounded-lg text-xs font-semibold border transition flex items-center gap-1.5 ${
              selectedStatus === 'ESCALATED'
                ? 'bg-rose-600 text-white border-rose-500 font-bold'
                : 'bg-slate-900/60 text-rose-400 border-rose-500/30 hover:bg-slate-900'
            }`}
          >
            <span className="h-1.5 w-1.5 rounded-full bg-rose-400" />
            Escalated ({statusCounts.ESCALATED})
          </button>

          <button
            onClick={() => setSelectedStatus('CLOSED')}
            className={`px-3 py-1.5 rounded-lg text-xs font-semibold border transition ${
              selectedStatus === 'CLOSED'
                ? 'bg-slate-700 text-white border-slate-600 font-bold'
                : 'bg-slate-900/60 text-slate-400 border-slate-800 hover:bg-slate-900'
            }`}
          >
            Closed ({statusCounts.CLOSED})
          </button>
        </div>
      </div>

      {/* Filter Toolbar */}
      <div className="rounded-xl border border-slate-800 bg-slate-900/60 p-4 flex flex-col md:flex-row items-center justify-between gap-3 text-xs">
        <form onSubmit={handleSearchSubmit} className="relative w-full md:w-96 flex items-center">
          <Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-500" />
          <input
            type="text"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search Alert ID, Customer Name..."
            className="w-full rounded-lg bg-slate-950 border border-slate-800 pl-9 pr-20 py-2 text-slate-200 placeholder-slate-500 focus:outline-none focus:border-indigo-500 text-xs"
          />
          <div className="absolute right-1.5 flex items-center gap-1">
            {search && (
              <button
                type="button"
                onClick={handleClearSearch}
                className="p-1 rounded text-slate-400 hover:text-white"
                title="Clear search"
              >
                <X className="h-3.5 w-3.5" />
              </button>
            )}
            <button
              type="submit"
              className="px-2.5 py-1 rounded bg-indigo-600 hover:bg-indigo-500 text-white font-semibold text-[11px] transition shadow-sm"
            >
              Search
            </button>
          </div>
        </form>

        <div className="flex flex-wrap items-center gap-3 w-full md:w-auto justify-end">
          <div className="flex items-center gap-2">
            <span className="text-slate-400">Priority:</span>
            <select
              value={selectedPriority}
              onChange={(e) => setSelectedPriority(e.target.value)}
              className="bg-slate-950 border border-slate-800 rounded-lg px-2.5 py-1.5 text-slate-200 focus:outline-none focus:border-indigo-500"
            >
              <option value="">All Priorities</option>
              <option value="CRITICAL">Critical Only</option>
              <option value="HIGH">High</option>
              <option value="MEDIUM">Medium</option>
              <option value="LOW">Low</option>
            </select>
          </div>

          <label className="flex items-center gap-2 cursor-pointer select-none text-slate-300">
            <input
              type="checkbox"
              checked={sarOnly}
              onChange={(e) => setSarOnly(e.target.checked)}
              className="rounded bg-slate-950 border-slate-800 text-indigo-600 focus:ring-0"
            />
            <span>SAR Candidates Only</span>
          </label>
        </div>
      </div>

      {/* Alerts Table */}
      <div className="rounded-xl border border-slate-800 bg-slate-900/40 overflow-hidden shadow-xl">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="bg-slate-950/80 border-b border-slate-800 text-slate-400 font-semibold uppercase tracking-wider">
              <tr>
                <th className="py-3.5 px-4">Alert Details</th>
                <th className="py-3.5 px-4">Customer Name / ID</th>
                <th className="py-3.5 px-4">Amount (INR)</th>
                <th className="py-3.5 px-4">Risk Evaluation</th>
                <th className="py-3.5 px-4">Triggered Rules</th>
                <th className="py-3.5 px-4">Status & Assignment</th>
                <th className="py-3.5 px-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/60">
              {loading ? (
                <tr>
                  <td colSpan={7} className="py-12 text-center text-slate-500">
                    Loading compliance alerts...
                  </td>
                </tr>
              ) : alerts.length === 0 ? (
                <tr>
                  <td colSpan={7} className="py-12 text-center text-slate-500">
                    No compliance alerts matching current filter criteria.
                  </td>
                </tr>
              ) : (
                alerts.map((alt) => (
                  <tr
                    key={alt._id}
                    onClick={() => onSelectAlert(alt.alertId)}
                    className="hover:bg-slate-800/40 transition cursor-pointer group"
                  >
                    {/* Alert Details */}
                    <td className="py-3.5 px-4">
                      <div className="flex items-center gap-2">
                        <span className="font-mono font-bold text-indigo-400 group-hover:text-indigo-300 transition">
                          {alt.alertId}
                        </span>
                        {alt.sarCandidate && (
                          <span className="px-1.5 py-0.5 rounded text-[10px] bg-purple-500/20 text-purple-300 border border-purple-500/40 font-bold">
                            SAR
                          </span>
                        )}
                      </div>
                      <div className="text-[11px] text-slate-500 mt-0.5 flex items-center gap-1 font-mono">
                        <Clock className="h-3 w-3" />
                        {formatDateTime(alt.createdAt)}
                      </div>
                    </td>

                    {/* Customer: Name & ID displayed clearly */}
                    <td className="py-3.5 px-4 text-slate-300">
                      <div
                        onClick={(e) => {
                          if (onViewCustomer) {
                            e.stopPropagation();
                            onViewCustomer(alt.customerId);
                          }
                        }}
                        className={`font-semibold text-white ${
                          onViewCustomer ? 'hover:text-indigo-300 hover:underline' : ''
                        }`}
                        title={onViewCustomer ? 'Click to inspect Customer Risk Profile' : ''}
                      >
                        {alt.customerName || alt.customerProfile?.fullName || 'Customer Profile'}
                      </div>
                      <div className="text-[11px] text-slate-400 font-mono mt-0.5 flex items-center gap-1">
                        <span>{alt.customerId}</span>
                        {alt.customerProfile?.occupation && (
                          <span className="text-slate-500 font-sans truncate max-w-[140px]">
                            &bull; {alt.customerProfile.occupation}
                          </span>
                        )}
                      </div>
                    </td>

                    {/* Amount */}
                    <td className="py-3.5 px-4">
                      <div className="font-mono font-bold text-slate-100">
                        {formatINR(alt.normalizedAmountINR)}
                      </div>
                      <span className="text-[10px] text-slate-500 uppercase">{alt.currency}</span>
                    </td>

                    {/* Risk */}
                    <td className="py-3.5 px-4">
                      <div className="flex items-center gap-2">
                        <div
                          className={`h-7 w-7 rounded-lg flex items-center justify-center font-mono font-bold text-xs ${
                            alt.riskScore >= 81
                              ? 'bg-rose-500/20 text-rose-400 border border-rose-500/40'
                              : alt.riskScore >= 61
                              ? 'bg-orange-500/20 text-orange-400 border border-orange-500/40'
                              : 'bg-yellow-500/20 text-yellow-400 border border-yellow-500/40'
                          }`}
                        >
                          {alt.riskScore}
                        </div>
                        <AlertPriorityBadge priority={alt.priority} />
                      </div>
                    </td>

                    {/* Rules */}
                    <td className="py-3.5 px-4">
                      <div className="flex flex-wrap gap-1 max-w-xs">
                        {alt.triggeredRules?.slice(0, 2).map((r, idx) => (
                          <span
                            key={idx}
                            className="px-1.5 py-0.5 rounded text-[10px] font-mono bg-slate-800 text-slate-300 border border-slate-700 truncate max-w-[140px]"
                            title={r.ruleName}
                          >
                            {r.ruleCode}
                          </span>
                        ))}
                        {alt.triggeredRules?.length > 2 && (
                          <span className="px-1 py-0.5 text-[10px] text-slate-500 font-mono">
                            +{alt.triggeredRules.length - 2} more
                          </span>
                        )}
                      </div>
                    </td>

                    {/* Status & Assignment */}
                    <td className="py-3.5 px-4">
                      <div className="space-y-1">
                        <AlertStatusBadge status={alt.status} />
                        <div className="text-[11px] text-slate-400 flex items-center gap-1">
                          <UserCheck className="h-3 w-3 text-slate-500" />
                          <span>{alt.assignedTo ? alt.assignedTo.fullName : 'Unassigned'}</span>
                        </div>
                      </div>
                    </td>

                    {/* Action */}
                    <td className="py-3.5 px-4 text-right">
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          onSelectAlert(alt.alertId);
                        }}
                        className="inline-flex items-center gap-1 px-3 py-1 rounded-lg bg-indigo-600/20 hover:bg-indigo-600 border border-indigo-500/30 hover:border-indigo-500 text-indigo-300 hover:text-white font-medium transition text-xs"
                      >
                        Investigate
                        <ChevronRight className="h-3.5 w-3.5" />
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default AlertManagementPage;
