/**
 * Synthetic financial data and money laundering simulation scenarios.
 * Strict compliance with privacy regulations: Contains ZERO real customer PII or banking data.
 */

export const SYNTHETIC_USERS = [
  {
    username: 'admin',
    email: 'admin@aml-platform.local',
    fullName: 'System Administrator',
    role: 'ADMIN',
    password: 'AdminPassword@2026'
  },
  {
    username: 'analyst',
    email: 'analyst@aml-platform.local',
    fullName: 'Vikram Mehta (Senior AML Analyst)',
    role: 'AML_ANALYST',
    password: 'AnalystPassword@2026'
  },
  {
    username: 'compliance',
    email: 'compliance@aml-platform.local',
    fullName: 'Ananya Sharma (Chief Compliance Officer)',
    role: 'COMPLIANCE_OFFICER',
    password: 'CompliancePassword@2026'
  }
];

export const SYNTHETIC_CUSTOMERS = [
  // Normal Salaried Customers (Low Risk)
  {
    customerId: 'CUST-IND-1001',
    fullName: 'Rohan Deshmukh',
    dob: new Date('1990-05-14'),
    gender: 'MALE',
    address: { street: '14 MG Road', city: 'Pune', state: 'Maharashtra', countryCode: 'IN', postalCode: '411001' },
    nationality: 'Indian',
    occupation: 'Software Engineer',
    monthlyIncome: 180000,
    accountType: 'SAVINGS',
    accountNumber: 'ACC-1001-987654',
    pepStatus: false,
    sanctioned: false,
    kycStatus: 'VERIFIED',
    riskCategory: 'LOW',
    customerRiskScore: 12,
    previousAlertCount: 0
  },
  {
    customerId: 'CUST-IND-1002',
    fullName: 'Pooja Iyer',
    dob: new Date('1988-11-20'),
    gender: 'FEMALE',
    address: { street: '22 Indiranagar 100ft Rd', city: 'Bengaluru', state: 'Karnataka', countryCode: 'IN', postalCode: '560038' },
    nationality: 'Indian',
    occupation: 'Doctor / Physician',
    monthlyIncome: 250000,
    accountType: 'SAVINGS',
    accountNumber: 'ACC-1002-876543',
    pepStatus: false,
    sanctioned: false,
    kycStatus: 'VERIFIED',
    riskCategory: 'LOW',
    customerRiskScore: 15,
    previousAlertCount: 0
  },

  // Scenario 1: Structuring / Smurfing Subject (High Risk)
  {
    customerId: 'CUST-IND-2001',
    fullName: 'Devendra Patel',
    dob: new Date('1982-03-08'),
    gender: 'MALE',
    address: { street: '78 Ashram Road', city: 'Ahmedabad', state: 'Gujarat', countryCode: 'IN', postalCode: '380009' },
    nationality: 'Indian',
    occupation: 'Real Estate Consultant',
    monthlyIncome: 80000, // Small monthly income compared to high structuring turnover
    accountType: 'CURRENT',
    accountNumber: 'ACC-2001-765432',
    pepStatus: false,
    sanctioned: false,
    kycStatus: 'VERIFIED',
    riskCategory: 'HIGH',
    customerRiskScore: 72,
    previousAlertCount: 1
  },

  // Scenario 2: Rapid In/Out Fund Mover (Critical Risk)
  {
    customerId: 'CUST-IND-3001',
    fullName: 'Kunal Singhania',
    dob: new Date('1995-07-29'),
    gender: 'MALE',
    address: { street: '5 Park Street', city: 'Kolkata', state: 'West Bengal', countryCode: 'IN', postalCode: '700016' },
    nationality: 'Indian',
    occupation: 'Cryptocurrency / Virtual Asset Broker',
    monthlyIncome: 120000,
    accountType: 'CURRENT',
    accountNumber: 'ACC-3001-654321',
    pepStatus: false,
    sanctioned: false,
    kycStatus: 'PENDING',
    riskCategory: 'CRITICAL',
    customerRiskScore: 84,
    previousAlertCount: 2
  },

  // Scenario 3: Layering Chain Entities (A -> B -> C -> D)
  {
    customerId: 'CUST-IND-4001',
    fullName: 'Apex Trading Corp (Entity A)',
    dob: new Date('2015-01-10'),
    gender: 'OTHER',
    address: { street: 'Plot 12 Nariman Point', city: 'Mumbai', state: 'Maharashtra', countryCode: 'IN', postalCode: '400021' },
    nationality: 'Indian',
    occupation: 'Import / Export Trader',
    monthlyIncome: 1500000,
    accountType: 'CORPORATE',
    accountNumber: 'ACC-4001-543210',
    pepStatus: false,
    sanctioned: false,
    kycStatus: 'VERIFIED',
    riskCategory: 'MEDIUM',
    customerRiskScore: 45,
    previousAlertCount: 0
  },
  {
    customerId: 'CUST-IND-4002',
    fullName: 'Blue Horizon Logistics (Entity B)',
    dob: new Date('2018-04-12'),
    gender: 'OTHER',
    address: { street: '44 Ring Road', city: 'Surat', state: 'Gujarat', countryCode: 'IN', postalCode: '395002' },
    nationality: 'Indian',
    occupation: 'Logistics Intermediary',
    monthlyIncome: 400000,
    accountType: 'CURRENT',
    accountNumber: 'ACC-4002-432109',
    pepStatus: false,
    sanctioned: false,
    kycStatus: 'VERIFIED',
    riskCategory: 'HIGH',
    customerRiskScore: 78,
    previousAlertCount: 1
  },
  {
    customerId: 'CUST-IND-4003',
    fullName: 'Crestfield Commercials (Entity C)',
    dob: new Date('2020-09-18'),
    gender: 'OTHER',
    address: { street: '9 Sector 18', city: 'Gurugram', state: 'Haryana', countryCode: 'IN', postalCode: '122008' },
    nationality: 'Indian',
    occupation: 'Wholesale Broker',
    monthlyIncome: 350000,
    accountType: 'CURRENT',
    accountNumber: 'ACC-4003-321098',
    pepStatus: false,
    sanctioned: false,
    kycStatus: 'VERIFIED',
    riskCategory: 'HIGH',
    customerRiskScore: 80,
    previousAlertCount: 1
  },
  {
    customerId: 'CUST-IND-4004',
    fullName: 'Deepak Verma (Entity D)',
    dob: new Date('1992-12-05'),
    gender: 'MALE',
    address: { street: '102 Karol Bagh', city: 'New Delhi', state: 'Delhi', countryCode: 'IN', postalCode: '110005' },
    nationality: 'Indian',
    occupation: 'Foreign Currency Exchange Dealer',
    monthlyIncome: 110000,
    accountType: 'SAVINGS',
    accountNumber: 'ACC-4004-210987',
    pepStatus: false,
    sanctioned: false,
    kycStatus: 'VERIFIED',
    riskCategory: 'CRITICAL',
    customerRiskScore: 88,
    previousAlertCount: 2
  },

  // Scenario 4: Politically Exposed Person (PEP) & High Risk Jurisdiction Subject
  {
    customerId: 'CUST-IND-5001',
    fullName: 'Rajeshwar Pratap Singh',
    dob: new Date('1965-08-15'),
    gender: 'MALE',
    address: { street: '1 Civil Lines', city: 'Lucknow', state: 'Uttar Pradesh', countryCode: 'IN', postalCode: '226001' },
    nationality: 'Indian',
    occupation: 'Politically Exposed Person (PEP)',
    monthlyIncome: 500000,
    accountType: 'CURRENT',
    accountNumber: 'ACC-5001-109876',
    pepStatus: true,
    sanctioned: false,
    kycStatus: 'VERIFIED',
    riskCategory: 'CRITICAL',
    customerRiskScore: 92,
    previousAlertCount: 3
  }
];

export const SYNTHETIC_TRANSACTIONS = [
  // 1. Legitimate Routine Transactions
  {
    transactionId: 'TXN-NORM-001',
    sourceCustomerId: 'CUST-IND-1001',
    sourceAccountId: 'ACC-1001-987654',
    destinationCustomerId: 'CUST-IND-1002',
    destinationAccountId: 'ACC-1002-876543',
    destinationBank: 'HDFC Bank',
    amount: 15000,
    currency: 'INR',
    normalizedAmountINR: 15000,
    transactionType: 'UPI',
    direction: 'DEBIT',
    channel: 'MOBILE_APP',
    location: { city: 'Pune', countryCode: 'IN', ipAddress: '49.36.12.80' },
    timestamp: new Date(Date.now() - 3600000 * 48),
    riskScore: 8,
    riskLevel: 'LOW',
    isSuspicious: false
  },
  {
    transactionId: 'TXN-NORM-002',
    sourceCustomerId: 'CUST-IND-1001',
    sourceAccountId: 'ACC-1001-987654',
    destinationCustomerId: null,
    destinationAccountId: 'ACC-RETAIL-5544',
    destinationBank: 'ICICI Bank',
    amount: 4500,
    currency: 'INR',
    normalizedAmountINR: 4500,
    transactionType: 'CARD',
    direction: 'DEBIT',
    channel: 'POS',
    location: { city: 'Pune', countryCode: 'IN', ipAddress: '49.36.12.80' },
    merchantDetails: { merchantId: 'MERCH-991', merchantName: 'Reliance Fresh Supermarket', mccCode: '5411' },
    timestamp: new Date(Date.now() - 3600000 * 24),
    riskScore: 5,
    riskLevel: 'LOW',
    isSuspicious: false
  },

  // 2. High Value Rule Trigger (₹15,00,000 >= ₹10,00,000 threshold)
  {
    transactionId: 'TXN-HIGH-VAL-001',
    sourceCustomerId: 'CUST-IND-1002',
    sourceAccountId: 'ACC-1002-876543',
    destinationCustomerId: 'CUST-IND-4001',
    destinationAccountId: 'ACC-4001-543210',
    destinationBank: 'State Bank of India',
    amount: 1500000,
    currency: 'INR',
    normalizedAmountINR: 1500000,
    transactionType: 'BANK_TRANSFER',
    direction: 'DEBIT',
    channel: 'NET_BANKING',
    location: { city: 'Bengaluru', countryCode: 'IN', ipAddress: '106.51.78.22' },
    timestamp: new Date(Date.now() - 3600000 * 12),
    riskScore: 68,
    riskLevel: 'HIGH',
    isSuspicious: true
  },

  // 3. Scenario 1: Structuring / Smurfing (₹4,80,000 + ₹4,90,000 + ₹4,75,000 within 24 hours)
  {
    transactionId: 'TXN-SMURF-001',
    sourceCustomerId: 'CUST-IND-2001',
    sourceAccountId: 'ACC-2001-765432',
    destinationCustomerId: null,
    destinationAccountId: 'ACC-2001-765432',
    destinationBank: 'Axis Bank',
    amount: 480000,
    currency: 'INR',
    normalizedAmountINR: 480000,
    transactionType: 'CASH_DEPOSIT',
    direction: 'CREDIT',
    channel: 'BRANCH',
    location: { city: 'Ahmedabad', countryCode: 'IN', ipAddress: '127.0.0.1' },
    timestamp: new Date(Date.now() - 3600000 * 18),
    riskScore: 78,
    riskLevel: 'HIGH',
    isSuspicious: true
  },
  {
    transactionId: 'TXN-SMURF-002',
    sourceCustomerId: 'CUST-IND-2001',
    sourceAccountId: 'ACC-2001-765432',
    destinationCustomerId: null,
    destinationAccountId: 'ACC-2001-765432',
    destinationBank: 'Axis Bank',
    amount: 490000,
    currency: 'INR',
    normalizedAmountINR: 490000,
    transactionType: 'CASH_DEPOSIT',
    direction: 'CREDIT',
    channel: 'BRANCH',
    location: { city: 'Ahmedabad', countryCode: 'IN', ipAddress: '127.0.0.1' },
    timestamp: new Date(Date.now() - 3600000 * 12),
    riskScore: 82,
    riskLevel: 'CRITICAL',
    isSuspicious: true
  },
  {
    transactionId: 'TXN-SMURF-003',
    sourceCustomerId: 'CUST-IND-2001',
    sourceAccountId: 'ACC-2001-765432',
    destinationCustomerId: null,
    destinationAccountId: 'ACC-2001-765432',
    destinationBank: 'Axis Bank',
    amount: 475000,
    currency: 'INR',
    normalizedAmountINR: 475000,
    transactionType: 'CASH_DEPOSIT',
    direction: 'CREDIT',
    channel: 'BRANCH',
    location: { city: 'Ahmedabad', countryCode: 'IN', ipAddress: '127.0.0.1' },
    timestamp: new Date(Date.now() - 3600000 * 4),
    riskScore: 89,
    riskLevel: 'CRITICAL',
    isSuspicious: true
  },

  // 4. Scenario 2: Rapid In/Out Movement (₹25,00,000 received and ₹23,50,000 immediately transferred out)
  {
    transactionId: 'TXN-RAPID-001',
    sourceCustomerId: 'CUST-IND-4001',
    sourceAccountId: 'ACC-4001-543210',
    destinationCustomerId: 'CUST-IND-3001',
    destinationAccountId: 'ACC-3001-654321',
    destinationBank: 'Kotak Mahindra Bank',
    amount: 2500000,
    currency: 'INR',
    normalizedAmountINR: 2500000,
    transactionType: 'BANK_TRANSFER',
    direction: 'CREDIT',
    channel: 'NET_BANKING',
    location: { city: 'Kolkata', countryCode: 'IN', ipAddress: '103.220.68.10' },
    timestamp: new Date(Date.now() - 60000 * 30),
    riskScore: 74,
    riskLevel: 'HIGH',
    isSuspicious: true
  },
  {
    transactionId: 'TXN-RAPID-002',
    sourceCustomerId: 'CUST-IND-3001',
    sourceAccountId: 'ACC-3001-654321',
    destinationCustomerId: null,
    destinationAccountId: 'ACC-CRYPTO-EXT-889',
    destinationBank: 'Offshore Crypto Gateway',
    amount: 2350000,
    currency: 'INR',
    normalizedAmountINR: 2350000,
    transactionType: 'INTERNATIONAL_TRANSFER',
    direction: 'DEBIT',
    channel: 'NET_BANKING',
    location: { city: 'Kolkata', countryCode: 'IN', ipAddress: '103.220.68.10' },
    timestamp: new Date(Date.now() - 60000 * 22), // 8 minutes after receipt
    riskScore: 94,
    riskLevel: 'CRITICAL',
    isSuspicious: true
  },

  // 5. Scenario 3: Layering Chain (A: ACC-4001-543210 -> B: ACC-4002-432109 -> C: ACC-4003-321098 -> D: ACC-4004-210987 -> Offshore)
  {
    transactionId: 'TXN-LAYER-001',
    sourceCustomerId: 'CUST-IND-4001',
    sourceAccountId: 'ACC-4001-543210',
    destinationCustomerId: 'CUST-IND-4002',
    destinationAccountId: 'ACC-4002-432109',
    destinationBank: 'IndusInd Bank',
    amount: 500000,
    currency: 'INR',
    normalizedAmountINR: 500000,
    transactionType: 'BANK_TRANSFER',
    direction: 'DEBIT',
    channel: 'NET_BANKING',
    location: { city: 'Mumbai', countryCode: 'IN', ipAddress: '115.111.45.10' },
    timestamp: new Date(Date.now() - 3600000 * 5),
    riskScore: 65,
    riskLevel: 'HIGH',
    isSuspicious: true
  },
  {
    transactionId: 'TXN-LAYER-002',
    sourceCustomerId: 'CUST-IND-4002',
    sourceAccountId: 'ACC-4002-432109',
    destinationCustomerId: 'CUST-IND-4003',
    destinationAccountId: 'ACC-4003-321098',
    destinationBank: 'Yes Bank',
    amount: 480000,
    currency: 'INR',
    normalizedAmountINR: 480000,
    transactionType: 'BANK_TRANSFER',
    direction: 'DEBIT',
    channel: 'NET_BANKING',
    location: { city: 'Surat', countryCode: 'IN', ipAddress: '115.111.45.10' },
    timestamp: new Date(Date.now() - 3600000 * 4),
    riskScore: 76,
    riskLevel: 'HIGH',
    isSuspicious: true
  },
  {
    transactionId: 'TXN-LAYER-003',
    sourceCustomerId: 'CUST-IND-4003',
    sourceAccountId: 'ACC-4003-321098',
    destinationCustomerId: 'CUST-IND-4004',
    destinationAccountId: 'ACC-4004-210987',
    destinationBank: 'Punjab National Bank',
    amount: 470000,
    currency: 'INR',
    normalizedAmountINR: 470000,
    transactionType: 'BANK_TRANSFER',
    direction: 'DEBIT',
    channel: 'NET_BANKING',
    location: { city: 'Gurugram', countryCode: 'IN', ipAddress: '115.111.45.10' },
    timestamp: new Date(Date.now() - 3600000 * 3),
    riskScore: 84,
    riskLevel: 'CRITICAL',
    isSuspicious: true
  },
  {
    transactionId: 'TXN-LAYER-004',
    sourceCustomerId: 'CUST-IND-4004',
    sourceAccountId: 'ACC-4004-210987',
    destinationCustomerId: null,
    destinationAccountId: 'ACC-OFFSHORE-PANAMA-99',
    destinationBank: 'Banco Panameño Offshore',
    amount: 460000,
    currency: 'INR',
    normalizedAmountINR: 460000,
    transactionType: 'INTERNATIONAL_TRANSFER',
    direction: 'DEBIT',
    channel: 'NET_BANKING',
    location: { city: 'New Delhi', countryCode: 'PA', ipAddress: '115.111.45.10' },
    timestamp: new Date(Date.now() - 3600000 * 2),
    riskScore: 96,
    riskLevel: 'CRITICAL',
    isSuspicious: true
  },

  // 6. Scenario 4: High-Risk Country Sanctions Corridor (Transfer to FATF Greylist / Blacklist)
  {
    transactionId: 'TXN-GEO-SANCTION-001',
    sourceCustomerId: 'CUST-IND-5001',
    sourceAccountId: 'ACC-5001-109876',
    destinationCustomerId: null,
    destinationAccountId: 'ACC-FOREIGN-IRAN-01',
    destinationBank: 'Bank Melli International',
    amount: 850000,
    currency: 'INR',
    normalizedAmountINR: 850000,
    transactionType: 'INTERNATIONAL_TRANSFER',
    direction: 'DEBIT',
    channel: 'NET_BANKING',
    location: { city: 'Lucknow', countryCode: 'IR', ipAddress: '182.72.4.9' }, // IR = Iran (FATF Blacklist)
    timestamp: new Date(Date.now() - 3600000 * 8),
    riskScore: 98,
    riskLevel: 'CRITICAL',
    isSuspicious: true
  }
];
